#应用全局
server:
  context-path: have
  port: 9999

#thymefeaf
spring:
  thymeleaf:
    enabled: false
    mode: HTML5
    check-template: true
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    cache: true

#访问认证
security:
  user:
    name: 1
    password: 1

#远程管理
management:
  address: 127.0.0.1
  port: 9090
  context-path: /manage
  security:
    role: SUPERUSER

#远程shutdown
endpoints:
  shutdown:
    enabled: true
    sensitive: true

#线程
thread:
  pool:
    size: 6

#自定义配置
my:
  config:
    name: yang
    id: 75
